import subprocess
import json
from utils.logger import logger

def build_prompt(candidate, job_description):
    name = candidate['personal_information'].get('name', 'Candidate')
    
    prompt = f"""
Act like a professional resume writer.
You are creating a job-specific resume for a candidate named {name}.

Here is the candidate's profile:
{json.dumps(candidate, indent=2)}

Here is the job description:
{job_description}

Generate a tailored resume in structured, professional English and ATS friendly. Focus on aligning experience, skills, and achievements to the job.
Use clear sections and bullet points. Do not fabricate any details.
Format the output in clean Markdown.
"""
    return prompt

def generate_resume_with_ollama(candidate, job_description, model="mistral"):
    try:
        prompt = build_prompt(candidate, job_description)

        result = subprocess.run(
            ["ollama", "run", model],
            input=prompt.encode('utf-8'),
            capture_output=True
        )

        output = result.stdout.decode('utf-8')
        logger.info("Resume generated by Mistral via Ollama.")
        return output

    except Exception as e:
        logger.error(f"Error generating resume with Ollama: {e}")
        return "Resume generation failed."
